name: js_import
description: Importing JS libraries and injection JS scripts into Flutter Web projects.
version: 1.0.2
repository: https://github.com/ivangalkindeveloper/js_import

environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
